// Generators for a self-contained mock server the caller downloads and runs.
//
// The hosted API expires in 24 hours. These files do not, work offline, and go
// in a repo — which is what someone actually wants once they have stopped
// experimenting. Giving people the exit is the strongest argument for trusting
// the front door.
//
// The reason to generate a server rather than hand over db.json and point at
// json-server: json-server cannot fail on purpose. These runners carry the same
// _delay, _status and _fail_rate that make the hosted API worth using, so the
// behaviour is identical locally and nothing has to be rewritten when someone
// moves from one to the other.
//
// Data is embedded as a JSON *string* and parsed at startup, never as a literal.
// In Python that is required — JSON's true/false/null are not Python's
// True/False/None, and interpolating them produces a file that raises NameError
// on the first boolean. In JavaScript it merely keeps parsing fast.

const embed = (data) => JSON.stringify(JSON.stringify(data));

export function nodeRunner(data) {
  return `#!/usr/bin/env node
// A mock API server. Generated by https://flakyapi.dev
//
//   node mock-server.mjs            # http://localhost:4000
//   node mock-server.mjs 5000       # another port
//
// No dependencies, no install, no network. Node 18 or newer.

import { createServer } from "node:http";

const DB = JSON.parse(${embed(data)});
const PORT = Number(process.argv[2]) || 4000;

// The same controls as flakyapi.dev, so behaviour does not change when you move
// between the hosted API and this file.
const MAX_DELAY = 10000;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const RESERVED = new Set([
  "_limit", "_page", "_start", "_sort", "_order", "_q", "_select",
  "_delay", "_status", "_fail_rate", "_malformed",
]);

const send = (res, status, body, headers = {}) => {
  const text = typeof body === "string" ? body : JSON.stringify(body);
  res.writeHead(status, {
    "content-type": "application/json; charset=utf-8",
    "access-control-allow-origin": "*",
    "access-control-allow-methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS",
    "access-control-allow-headers": "content-type, authorization",
    "access-control-expose-headers": "x-total-count",
    ...headers,
  });
  res.end(text);
};

const fail = (res, status, message, hint) => send(res, status, { error: { status, message, hint } });

function query(rows, params) {
  let result = rows;

  for (const [field, value] of params) {
    if (RESERVED.has(field)) continue;
    result = result.filter((row) => String(row?.[field]) === value);
  }

  const q = params.get("_q");
  if (q) {
    const needle = q.toLowerCase();
    result = result.filter((row) => JSON.stringify(row).toLowerCase().includes(needle));
  }

  const sort = params.get("_sort");
  if (sort) {
    const dir = params.get("_order") === "desc" ? -1 : 1;
    result = [...result].sort((a, b) => (a[sort] > b[sort] ? dir : a[sort] < b[sort] ? -dir : 0));
  }

  const select = params.get("_select");
  if (select) {
    const fields = new Set(select.split(",").map((f) => f.trim()).filter(Boolean));
    fields.add("id");
    result = result.map((row) => Object.fromEntries(Object.entries(row).filter(([k]) => fields.has(k))));
  }

  const total = result.length;
  const limit = Number(params.get("_limit")) || total || 1;
  const start = params.has("_start")
    ? Math.max(Number(params.get("_start")) || 0, 0)
    : (Math.max(Number(params.get("_page")) || 1, 1) - 1) * limit;

  return { rows: result.slice(start, start + limit), total };
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url, "http://localhost");
  const params = url.searchParams;

  if (req.method === "OPTIONS") return send(res, 204, "");

  // Chaos first, so a forced failure costs nothing to produce.
  const delay = Number(params.get("_delay"));
  if (delay > 0) await sleep(Math.min(delay, MAX_DELAY));

  const rate = Number(params.get("_fail_rate"));
  if (rate > 0 && Math.random() < rate) {
    return fail(res, 500, "Injected failure", \`Lost the dice roll for _fail_rate=\${rate}.\`);
  }

  const forced = Number(params.get("_status"));
  if (forced >= 100 && forced <= 599 && forced !== 200) {
    const extra = forced === 429 || forced === 503 ? { "retry-after": "5" } : {};
    return send(res, forced, { error: { status: forced, message: "Injected status" } }, extra);
  }

  const [resource, id] = url.pathname.split("/").filter(Boolean);

  if (!resource) {
    return send(res, 200, {
      server: "flaky local mock",
      resources: Object.entries(DB).map(([name, rows]) => ({ name, count: rows.length, url: \`/\${name}\` })),
      controls: ["_delay", "_status", "_fail_rate", "_malformed", "_limit", "_page", "_start", "_sort", "_order", "_q", "_select"],
    });
  }

  const rows = DB[resource];
  if (!rows) return fail(res, 404, \`No '\${resource}' here\`, \`Available: \${Object.keys(DB).join(", ")}.\`);

  if (id) {
    const found = rows.find((row) => String(row?.id) === id);
    return found ? send(res, 200, found) : fail(res, 404, \`No \${resource} with id \${id}\`);
  }

  const page = query(rows, params);
  let body = JSON.stringify(page.rows);

  // Truncated mid-record, as a dropped connection would be.
  if (params.get("_malformed") === "1") body = body.slice(0, Math.max(1, Math.floor(body.length * 0.6)));

  send(res, 200, body, { "x-total-count": String(page.total) });
});

server.listen(PORT, () => {
  console.log(\`\\n  flaky mock server → http://localhost:\${PORT}\\n\`);
  for (const [name, rows] of Object.entries(DB)) {
    console.log(\`    /\${name.padEnd(20)} \${String(rows.length).padStart(5)} records\`);
  }
  console.log(\`\\n  Break it on purpose:\`);
  const first = Object.keys(DB)[0];
  console.log(\`    http://localhost:\${PORT}/\${first}?_delay=3000\`);
  console.log(\`    http://localhost:\${PORT}/\${first}?_status=503\`);
  console.log(\`    http://localhost:\${PORT}/\${first}?_fail_rate=0.3\\n\`);
});
`;
}

export function pythonRunner(data) {
  return `#!/usr/bin/env python3
"""A mock API server. Generated by https://flakyapi.dev

    python3 mock_server.py          # http://localhost:4000
    python3 mock_server.py 5000     # another port

Standard library only. No pip install, no network.
"""

import json
import random
import sys
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

# Parsed from a string rather than written as a literal: JSON's true, false and
# null are not Python's True, False and None, and pasting them straight in
# produces a file that raises NameError on the first boolean.
DB = json.loads(${embed(data)})

PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 4000
MAX_DELAY = 10.0

RESERVED = {"_limit", "_page", "_start", "_sort", "_order", "_q", "_select",
            "_delay", "_status", "_fail_rate", "_malformed"}


def one(params, name, default=None):
    return params.get(name, [default])[0]


def as_text(value):
    """Compare the way JSON spells things, not the way Python does.

    str(True) is "True" and str(None) is "None", so ?done=true matched nothing
    and the filter silently returned an empty list — the same class of mismatch
    that makes embedding JSON as a Python literal fail on the first boolean.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def query(rows, params):
    result = rows

    for field, values in params.items():
        if field in RESERVED:
            continue
        result = [r for r in result if as_text(r.get(field)) == values[0]]

    q = one(params, "_q")
    if q:
        result = [r for r in result if q.lower() in json.dumps(r).lower()]

    sort = one(params, "_sort")
    if sort:
        result = sorted(result, key=lambda r: (r.get(sort) is None, r.get(sort)),
                        reverse=one(params, "_order") == "desc")

    select = one(params, "_select")
    if select:
        fields = {f.strip() for f in select.split(",") if f.strip()} | {"id"}
        result = [{k: v for k, v in r.items() if k in fields} for r in result]

    total = len(result)
    limit = int(one(params, "_limit") or total or 1)
    if "_start" in params:
        start = max(int(one(params, "_start") or 0), 0)
    else:
        start = (max(int(one(params, "_page") or 1), 1) - 1) * limit

    return result[start:start + limit], total


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        print("  %s %s" % (self.command, self.path))

    def _send(self, status, payload, extra=None):
        body = payload if isinstance(payload, str) else json.dumps(payload)
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "content-type, authorization")
        self.send_header("Access-Control-Expose-Headers", "x-total-count")
        for key, value in (extra or {}).items():
            self.send_header(key, value)
        self.end_headers()
        self.wfile.write(body.encode())

    def _fail(self, status, message, hint=""):
        self._send(status, {"error": {"status": status, "message": message, "hint": hint}})

    def do_OPTIONS(self):
        self._send(204, "")

    def do_GET(self):
        parsed = urlparse(self.path)
        params = parse_qs(parsed.query)

        delay = float(one(params, "_delay") or 0)
        if delay > 0:
            time.sleep(min(delay / 1000.0, MAX_DELAY))

        rate = float(one(params, "_fail_rate") or 0)
        if rate > 0 and random.random() < rate:
            return self._fail(500, "Injected failure", "Lost the dice roll for _fail_rate=%s." % rate)

        forced = int(one(params, "_status") or 0)
        if 100 <= forced <= 599 and forced != 200:
            extra = {"Retry-After": "5"} if forced in (429, 503) else {}
            return self._send(forced, {"error": {"status": forced, "message": "Injected status"}}, extra)

        parts = [p for p in parsed.path.split("/") if p]

        if not parts:
            return self._send(200, {
                "server": "flaky local mock",
                "resources": [{"name": n, "count": len(r), "url": "/" + n} for n, r in DB.items()],
                "controls": sorted(RESERVED),
            })

        resource = parts[0]
        if resource not in DB:
            return self._fail(404, "No '%s' here" % resource, "Available: %s." % ", ".join(DB))

        if len(parts) > 1:
            found = next((r for r in DB[resource] if as_text(r.get("id")) == parts[1]), None)
            return self._send(200, found) if found else self._fail(404, "No %s with id %s" % (resource, parts[1]))

        rows, total = query(DB[resource], params)
        body = json.dumps(rows)
        if one(params, "_malformed") == "1":
            body = body[:max(1, int(len(body) * 0.6))]

        self._send(200, body, {"x-total-count": str(total)})


if __name__ == "__main__":
    print("\\n  flaky mock server -> http://localhost:%d\\n" % PORT)
    for name, rows in DB.items():
        print("    /%-20s %5d records" % (name, len(rows)))
    first = next(iter(DB), "items")
    print("\\n  Break it on purpose:")
    print("    http://localhost:%d/%s?_delay=3000" % (PORT, first))
    print("    http://localhost:%d/%s?_status=503" % (PORT, first))
    print("    http://localhost:%d/%s?_fail_rate=0.3\\n" % (PORT, first))
    ThreadingHTTPServer(("", PORT), Handler).serve_forever()
`;
}
