// Generators for a self-contained mock server the caller downloads and runs.
//
// The hosted API expires in 24 hours. These files do not, work offline, and go
// in a repo — which is what someone actually wants once they have stopped
// experimenting. Giving people the exit is the strongest argument for trusting
// the front door.
//
// The reason to generate a server rather than hand over db.json and point at
// json-server: json-server cannot fail on purpose. These runners carry the same
// _delay, _status and _fail_rate that make the hosted API worth using, so the
// behaviour is identical locally and nothing has to be rewritten when someone
// moves from one to the other.
//
// Data is embedded as a JSON *string* and parsed at startup, never as a literal.
// In Python that is required — JSON's true/false/null are not Python's
// True/False/None, and interpolating them produces a file that raises NameError
// on the first boolean. In JavaScript it merely keeps parsing fast.

const embed = (data) => JSON.stringify(JSON.stringify(data));

// Java caps a single constant in a class file at 64 KB and a paste can be four
// times that, so the data goes in as chunks that are joined before parsing. The
// split happens on the *unescaped* JSON and each piece is escaped whole —
// slicing the escaped text would eventually cut a \" or a \uXXXX in half.
//
// Non-ASCII is escaped too: javac only defaults to UTF-8 from JDK 18, and on an
// older one a source file full of accented names is read in the platform
// encoding and silently corrupted.
const JAVA_CHUNK = 8000;

const embedChunks = (data) => {
  const json = JSON.stringify(data);
  const pieces = [];
  for (let i = 0; i < json.length; i += JAVA_CHUNK) pieces.push(json.slice(i, i + JAVA_CHUNK));
  if (!pieces.length) pieces.push("");

  return pieces
    .map((piece) => JSON.stringify(piece).replace(/[^\x20-\x7e]/g, (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0")))
    .map((literal) => "    " + literal)
    .join(",\n");
};

export function nodeRunner(data) {
  return `#!/usr/bin/env node
// A mock API server. Generated by https://flakyapi.dev
//
//   node mock-server.mjs            # http://localhost:4000
//   node mock-server.mjs 5000       # another port
//
// No dependencies, no install, no network. Node 18 or newer.

import { createServer } from "node:http";

const DB = JSON.parse(${embed(data)});
const PORT = Number(process.argv[2]) || 4000;

// The same controls as flakyapi.dev, so behaviour does not change when you move
// between the hosted API and this file.
const MAX_DELAY = 10000;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const RESERVED = new Set([
  "_limit", "_page", "_start", "_sort", "_order", "_q", "_select",
  "_delay", "_status", "_fail_rate", "_malformed",
]);

const send = (res, status, body, headers = {}) => {
  const text = typeof body === "string" ? body : JSON.stringify(body);
  res.writeHead(status, {
    "content-type": "application/json; charset=utf-8",
    "access-control-allow-origin": "*",
    "access-control-allow-methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS",
    "access-control-allow-headers": "content-type, authorization",
    "access-control-expose-headers": "x-total-count",
    ...headers,
  });
  res.end(text);
};

const fail = (res, status, message, hint) => send(res, status, { error: { status, message, hint } });

function query(rows, params) {
  let result = rows;

  for (const [field, value] of params) {
    if (RESERVED.has(field)) continue;
    result = result.filter((row) => String(row?.[field]) === value);
  }

  const q = params.get("_q");
  if (q) {
    const needle = q.toLowerCase();
    result = result.filter((row) => JSON.stringify(row).toLowerCase().includes(needle));
  }

  const sort = params.get("_sort");
  if (sort) {
    const dir = params.get("_order") === "desc" ? -1 : 1;
    // Nulls last, explicitly. Comparing them with > and < coerces null to 0, so
    // a missing value sorted between -1 and 1 and the four runners disagreed
    // about where it went.
    const rank = (a, b) => {
      if (a === null || a === undefined) return b === null || b === undefined ? 0 : 1;
      if (b === null || b === undefined) return -1;
      return a > b ? 1 : a < b ? -1 : 0;
    };
    result = [...result].sort((a, b) => dir * rank(a[sort], b[sort]));
  }

  const select = params.get("_select");
  if (select) {
    const fields = new Set(select.split(",").map((f) => f.trim()).filter(Boolean));
    fields.add("id");
    result = result.map((row) => Object.fromEntries(Object.entries(row).filter(([k]) => fields.has(k))));
  }

  const total = result.length;
  const limit = Number(params.get("_limit")) || total || 1;
  const start = params.has("_start")
    ? Math.max(Number(params.get("_start")) || 0, 0)
    : (Math.max(Number(params.get("_page")) || 1, 1) - 1) * limit;

  return { rows: result.slice(start, start + limit), total };
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url, "http://localhost");
  const params = url.searchParams;

  if (req.method === "OPTIONS") return send(res, 204, "");

  // Chaos first, so a forced failure costs nothing to produce.
  const delay = Number(params.get("_delay"));
  if (delay > 0) await sleep(Math.min(delay, MAX_DELAY));

  const rate = Number(params.get("_fail_rate"));
  if (rate > 0 && Math.random() < rate) {
    return fail(res, 500, "Injected failure", \`Lost the dice roll for _fail_rate=\${rate}.\`);
  }

  const forced = Number(params.get("_status"));
  if (forced >= 100 && forced <= 599 && forced !== 200) {
    const extra = forced === 429 || forced === 503 ? { "retry-after": "5" } : {};
    return send(res, forced, { error: { status: forced, message: "Injected status" } }, extra);
  }

  const [resource, id] = url.pathname.split("/").filter(Boolean);

  if (!resource) {
    return send(res, 200, {
      server: "flaky local mock",
      resources: Object.entries(DB).map(([name, rows]) => ({ name, count: rows.length, url: \`/\${name}\` })),
      controls: ["_delay", "_status", "_fail_rate", "_malformed", "_limit", "_page", "_start", "_sort", "_order", "_q", "_select"],
    });
  }

  const rows = DB[resource];
  if (!rows) return fail(res, 404, \`No '\${resource}' here\`, \`Available: \${Object.keys(DB).join(", ")}.\`);

  if (id) {
    const found = rows.find((row) => String(row?.id) === id);
    return found ? send(res, 200, found) : fail(res, 404, \`No \${resource} with id \${id}\`);
  }

  const page = query(rows, params);
  let body = JSON.stringify(page.rows);

  // Truncated mid-record, as a dropped connection would be.
  if (params.get("_malformed") === "1") body = body.slice(0, Math.max(1, Math.floor(body.length * 0.6)));

  send(res, 200, body, { "x-total-count": String(page.total) });
});

server.listen(PORT, () => {
  console.log(\`\\n  flaky mock server → http://localhost:\${PORT}\\n\`);
  for (const [name, rows] of Object.entries(DB)) {
    console.log(\`    /\${name.padEnd(20)} \${String(rows.length).padStart(5)} records\`);
  }
  console.log(\`\\n  Break it on purpose:\`);
  const first = Object.keys(DB)[0];
  console.log(\`    http://localhost:\${PORT}/\${first}?_delay=3000\`);
  console.log(\`    http://localhost:\${PORT}/\${first}?_status=503\`);
  console.log(\`    http://localhost:\${PORT}/\${first}?_fail_rate=0.3\\n\`);
});
`;
}

export function pythonRunner(data) {
  return `#!/usr/bin/env python3
"""A mock API server. Generated by https://flakyapi.dev

    python3 mock_server.py          # http://localhost:4000
    python3 mock_server.py 5000     # another port

Standard library only. No pip install, no network.
"""

import json
import random
import sys
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

# Parsed from a string rather than written as a literal: JSON's true, false and
# null are not Python's True, False and None, and pasting them straight in
# produces a file that raises NameError on the first boolean.
DB = json.loads(${embed(data)})

PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 4000
MAX_DELAY = 10.0

CONTROLS = ["_delay", "_status", "_fail_rate", "_malformed",
            "_limit", "_page", "_start", "_sort", "_order", "_q", "_select"]

RESERVED = set(CONTROLS)


def one(params, name, default=None):
    return params.get(name, [default])[0]


def dumps(value):
    """Compact and unescaped, so the bytes match the hosted API and the other
    runners. Python's defaults put a space after every separator and escape
    every non-ASCII character, which is valid JSON but different bytes — and
    _malformed truncates at a fraction of the body, so the cut moved too.
    """
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False)


def as_text(value):
    """Compare the way JSON spells things, not the way Python does.

    str(True) is "True" and str(None) is "None", so ?done=true matched nothing
    and the filter silently returned an empty list — the same class of mismatch
    that makes embedding JSON as a Python literal fail on the first boolean.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def query(rows, params):
    result = rows

    for field, values in params.items():
        if field in RESERVED:
            continue
        result = [r for r in result if as_text(r.get(field)) == values[0]]

    q = one(params, "_q")
    if q:
        result = [r for r in result if q.lower() in dumps(r).lower()]

    sort = one(params, "_sort")
    if sort:
        result = sorted(result, key=lambda r: (r.get(sort) is None, r.get(sort)),
                        reverse=one(params, "_order") == "desc")

    select = one(params, "_select")
    if select:
        fields = {f.strip() for f in select.split(",") if f.strip()} | {"id"}
        result = [{k: v for k, v in r.items() if k in fields} for r in result]

    total = len(result)
    limit = int(one(params, "_limit") or total or 1)
    if "_start" in params:
        start = max(int(one(params, "_start") or 0), 0)
    else:
        start = (max(int(one(params, "_page") or 1), 1) - 1) * limit

    return result[start:start + limit], total


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        print("  %s %s" % (self.command, self.path))

    def _send(self, status, payload, extra=None):
        body = payload if isinstance(payload, str) else dumps(payload)
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "content-type, authorization")
        self.send_header("Access-Control-Expose-Headers", "x-total-count")
        for key, value in (extra or {}).items():
            self.send_header(key, value)
        self.end_headers()
        self.wfile.write(body.encode())

    def _fail(self, status, message, hint=""):
        error = {"status": status, "message": message}
        if hint:
            error["hint"] = hint
        self._send(status, {"error": error})

    def do_OPTIONS(self):
        self._send(204, "")

    def do_GET(self):
        parsed = urlparse(self.path)
        params = parse_qs(parsed.query)

        delay = float(one(params, "_delay") or 0)
        if delay > 0:
            time.sleep(min(delay / 1000.0, MAX_DELAY))

        rate = float(one(params, "_fail_rate") or 0)
        if rate > 0 and random.random() < rate:
            # The raw value, not the parsed float: "1" was reported back as "1.0".
            return self._fail(500, "Injected failure",
                              "Lost the dice roll for _fail_rate=%s." % one(params, "_fail_rate"))

        forced = int(one(params, "_status") or 0)
        if 100 <= forced <= 599 and forced != 200:
            extra = {"Retry-After": "5"} if forced in (429, 503) else {}
            return self._send(forced, {"error": {"status": forced, "message": "Injected status"}}, extra)

        parts = [p for p in parsed.path.split("/") if p]

        if not parts:
            return self._send(200, {
                "server": "flaky local mock",
                "resources": [{"name": n, "count": len(r), "url": "/" + n} for n, r in DB.items()],
                "controls": CONTROLS,
            })

        resource = parts[0]
        if resource not in DB:
            return self._fail(404, "No '%s' here" % resource, "Available: %s." % ", ".join(DB))

        if len(parts) > 1:
            found = next((r for r in DB[resource] if as_text(r.get("id")) == parts[1]), None)
            return self._send(200, found) if found else self._fail(404, "No %s with id %s" % (resource, parts[1]))

        rows, total = query(DB[resource], params)
        body = dumps(rows)
        if one(params, "_malformed") == "1":
            body = body[:max(1, int(len(body) * 0.6))]

        self._send(200, body, {"x-total-count": str(total)})


if __name__ == "__main__":
    print("\\n  flaky mock server -> http://localhost:%d\\n" % PORT)
    for name, rows in DB.items():
        print("    /%-20s %5d records" % (name, len(rows)))
    first = next(iter(DB), "items")
    print("\\n  Break it on purpose:")
    print("    http://localhost:%d/%s?_delay=3000" % (PORT, first))
    print("    http://localhost:%d/%s?_status=503" % (PORT, first))
    print("    http://localhost:%d/%s?_fail_rate=0.3\\n" % (PORT, first))
    ThreadingHTTPServer(("", PORT), Handler).serve_forever()
`;
}

export function javaRunner(data) {
  return `// A mock API server. Generated by https://flakyapi.dev
//
//   java MockServer.java            # http://localhost:4000
//   java MockServer.java 5000       # another port
//
// No dependencies, no build step, no network. A JDK of 11 or newer runs a
// single .java file directly. The JSON parser at the bottom is here because the
// JDK ships none, and one file that runs beats four that need Jackson.

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.concurrent.Executors;

public class MockServer {

  // Embedded as a string and parsed at startup, never as Java literals: JSON's
  // true/false/null are not Java's spelling of them everywhere they appear, and
  // a class file caps a single constant at 64 KB - so the data arrives in
  // chunks and is joined before it is parsed.
  static final String[] DATA = {
${embedChunks(data)}
  };

  static final Map<String, List<Object>> DB = new LinkedHashMap<String, List<Object>>();

  // The same controls as flakyapi.dev, so behaviour does not change when you
  // move between the hosted API and this file.
  static final List<Object> CONTROLS = Arrays.<Object>asList(
      "_delay", "_status", "_fail_rate", "_malformed",
      "_limit", "_page", "_start", "_sort", "_order", "_q", "_select");

  static final Set<String> RESERVED = new HashSet<String>(Arrays.asList(
      "_limit", "_page", "_start", "_sort", "_order", "_q", "_select",
      "_delay", "_status", "_fail_rate", "_malformed"));

  static final long MAX_DELAY = 10000;
  static final Random RANDOM = new Random();

  // ---------------------------------------------------------------- helpers

  /** Compare the way JSON spells things, not the way Java does.
   *
   * A JSON 1 read as a double prints back as "1.0", so ?userId=1 would match
   * nothing and the filter would silently return an empty list. */
  static String text(Object value) {
    if (value == null) return "null";
    if (value instanceof Double) {
      double d = ((Double) value).doubleValue();
      if (!Double.isInfinite(d) && !Double.isNaN(d) && d == Math.rint(d) && Math.abs(d) < 1e15) {
        return String.valueOf((long) d);
      }
    }
    return String.valueOf(value);
  }

  @SuppressWarnings("unchecked")
  static Map<String, Object> row(Object value) {
    return value instanceof Map ? (Map<String, Object>) value : new LinkedHashMap<String, Object>();
  }

  static double num(String raw, double fallback) {
    if (raw == null || raw.isEmpty()) return fallback;
    try {
      return Double.parseDouble(raw);
    } catch (NumberFormatException e) {
      return fallback;
    }
  }

  static String decode(String raw) {
    try {
      return URLDecoder.decode(raw, "UTF-8");
    } catch (Exception e) {
      return raw;
    }
  }

  /** First value wins, which is what the other runners do too. */
  static Map<String, String> params(String raw) {
    Map<String, String> out = new LinkedHashMap<String, String>();
    if (raw == null || raw.isEmpty()) return out;
    for (String pair : raw.split("&")) {
      if (pair.isEmpty()) continue;
      int eq = pair.indexOf('=');
      String key = eq < 0 ? pair : pair.substring(0, eq);
      String value = eq < 0 ? "" : pair.substring(eq + 1);
      if (!out.containsKey(decode(key))) out.put(decode(key), decode(value));
    }
    return out;
  }

  @SuppressWarnings({"unchecked", "rawtypes"})
  static int compare(Object a, Object b) {
    if (a == null) return b == null ? 0 : 1;
    if (b == null) return -1;
    if (a instanceof Number && b instanceof Number) {
      return Double.compare(((Number) a).doubleValue(), ((Number) b).doubleValue());
    }
    if (a instanceof Comparable && a.getClass() == b.getClass()) return ((Comparable) a).compareTo(b);
    return text(a).compareTo(text(b));
  }

  // ------------------------------------------------------------------ query

  static final class Page {
    final List<Object> rows;
    final int total;

    Page(List<Object> rows, int total) {
      this.rows = rows;
      this.total = total;
    }
  }

  static Page query(List<Object> rows, Map<String, String> params) {
    List<Object> result = new ArrayList<Object>(rows);

    for (Map.Entry<String, String> entry : params.entrySet()) {
      if (RESERVED.contains(entry.getKey())) continue;
      List<Object> kept = new ArrayList<Object>();
      for (Object item : result) {
        if (text(row(item).get(entry.getKey())).equals(entry.getValue())) kept.add(item);
      }
      result = kept;
    }

    String q = params.get("_q");
    if (q != null && !q.isEmpty()) {
      String needle = q.toLowerCase();
      List<Object> kept = new ArrayList<Object>();
      for (Object item : result) {
        if (Json.write(item).toLowerCase().contains(needle)) kept.add(item);
      }
      result = kept;
    }

    final String sort = params.get("_sort");
    if (sort != null && !sort.isEmpty()) {
      final int dir = "desc".equals(params.get("_order")) ? -1 : 1;
      Collections.sort(result, (a, b) -> dir * compare(row(a).get(sort), row(b).get(sort)));
    }

    String select = params.get("_select");
    if (select != null && !select.isEmpty()) {
      Set<String> fields = new HashSet<String>();
      for (String field : select.split(",")) {
        if (!field.trim().isEmpty()) fields.add(field.trim());
      }
      fields.add("id");
      List<Object> shaped = new ArrayList<Object>();
      for (Object item : result) {
        Map<String, Object> slim = new LinkedHashMap<String, Object>();
        for (Map.Entry<String, Object> entry : row(item).entrySet()) {
          if (fields.contains(entry.getKey())) slim.put(entry.getKey(), entry.getValue());
        }
        shaped.add(slim);
      }
      result = shaped;
    }

    int total = result.size();
    int limit = (int) num(params.get("_limit"), 0);
    if (limit <= 0) limit = total > 0 ? total : 1;

    int start;
    if (params.containsKey("_start")) {
      start = Math.max((int) num(params.get("_start"), 0), 0);
    } else {
      start = (Math.max((int) num(params.get("_page"), 1), 1) - 1) * limit;
    }

    if (start >= total) return new Page(new ArrayList<Object>(), total);
    return new Page(new ArrayList<Object>(result.subList(start, Math.min(start + limit, total))), total);
  }

  // ------------------------------------------------------------------- http

  static void send(HttpExchange exchange, int status, String body, Map<String, String> extra) throws IOException {
    exchange.getResponseHeaders().set("Content-Type", "application/json; charset=utf-8");
    exchange.getResponseHeaders().set("Access-Control-Allow-Origin", "*");
    exchange.getResponseHeaders().set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS");
    exchange.getResponseHeaders().set("Access-Control-Allow-Headers", "content-type, authorization");
    exchange.getResponseHeaders().set("Access-Control-Expose-Headers", "x-total-count");
    if (extra != null) {
      for (Map.Entry<String, String> entry : extra.entrySet()) {
        exchange.getResponseHeaders().set(entry.getKey(), entry.getValue());
      }
    }

    // A 204 carries no body, and the JDK server rejects a length for one.
    if (status == 204) {
      exchange.sendResponseHeaders(status, -1);
      exchange.close();
      return;
    }

    byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
    exchange.sendResponseHeaders(status, bytes.length);
    OutputStream out = exchange.getResponseBody();
    try {
      out.write(bytes);
    } finally {
      out.close();
    }
  }

  static String errorBody(int status, String message, String hint) {
    Map<String, Object> error = new LinkedHashMap<String, Object>();
    error.put("status", Long.valueOf(status));
    error.put("message", message);
    if (hint != null) error.put("hint", hint);
    Map<String, Object> body = new LinkedHashMap<String, Object>();
    body.put("error", error);
    return Json.write(body);
  }

  static void fail(HttpExchange exchange, int status, String message, String hint) throws IOException {
    send(exchange, status, errorBody(status, message, hint), null);
  }

  static void handle(HttpExchange exchange) throws IOException {
    System.out.println("  " + exchange.getRequestMethod() + " " + exchange.getRequestURI());
    Map<String, String> params = params(exchange.getRequestURI().getRawQuery());

    if ("OPTIONS".equals(exchange.getRequestMethod())) {
      send(exchange, 204, "", null);
      return;
    }

    // Chaos first, so a forced failure costs nothing to produce.
    double delay = num(params.get("_delay"), 0);
    if (delay > 0) {
      try {
        Thread.sleep((long) Math.min(delay, MAX_DELAY));
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
      }
    }

    double rate = num(params.get("_fail_rate"), 0);
    if (rate > 0 && RANDOM.nextDouble() < rate) {
      fail(exchange, 500, "Injected failure", "Lost the dice roll for _fail_rate=" + params.get("_fail_rate") + ".");
      return;
    }

    int forced = (int) num(params.get("_status"), 0);
    if (forced >= 100 && forced <= 599 && forced != 200) {
      Map<String, String> extra = (forced == 429 || forced == 503)
          ? Collections.singletonMap("Retry-After", "5")
          : null;
      send(exchange, forced, errorBody(forced, "Injected status", null), extra);
      return;
    }

    List<String> parts = new ArrayList<String>();
    for (String part : exchange.getRequestURI().getPath().split("/")) {
      if (!part.isEmpty()) parts.add(decode(part));
    }

    if (parts.isEmpty()) {
      List<Object> resources = new ArrayList<Object>();
      for (Map.Entry<String, List<Object>> entry : DB.entrySet()) {
        Map<String, Object> resource = new LinkedHashMap<String, Object>();
        resource.put("name", entry.getKey());
        resource.put("count", Long.valueOf(entry.getValue().size()));
        resource.put("url", "/" + entry.getKey());
        resources.add(resource);
      }
      Map<String, Object> body = new LinkedHashMap<String, Object>();
      body.put("server", "flaky local mock");
      body.put("resources", resources);
      body.put("controls", CONTROLS);
      send(exchange, 200, Json.write(body), null);
      return;
    }

    String resource = parts.get(0);
    List<Object> rows = DB.get(resource);
    if (rows == null) {
      fail(exchange, 404, "No '" + resource + "' here", "Available: " + String.join(", ", DB.keySet()) + ".");
      return;
    }

    if (parts.size() > 1) {
      String id = parts.get(1);
      for (Object item : rows) {
        if (text(row(item).get("id")).equals(id)) {
          send(exchange, 200, Json.write(item), null);
          return;
        }
      }
      fail(exchange, 404, "No " + resource + " with id " + id, null);
      return;
    }

    Page page = query(rows, params);
    String body = Json.write(page.rows);

    // Truncated mid-record, as a dropped connection would be.
    if ("1".equals(params.get("_malformed"))) {
      body = body.substring(0, Math.max(1, (int) (body.length() * 0.6)));
    }

    send(exchange, 200, body, Collections.singletonMap("x-total-count", String.valueOf(page.total)));
  }

  // ------------------------------------------------------------------- main

  @SuppressWarnings("unchecked")
  public static void main(String[] args) throws IOException {
    int port = args.length > 0 ? Integer.parseInt(args[0]) : 4000;

    StringBuilder raw = new StringBuilder();
    for (String chunk : DATA) raw.append(chunk);
    Object parsed = Json.parse(raw.toString());

    for (Map.Entry<String, Object> entry : ((Map<String, Object>) parsed).entrySet()) {
      if (entry.getValue() instanceof List) DB.put(entry.getKey(), (List<Object>) entry.getValue());
    }

    System.out.println();
    System.out.println("  flaky mock server -> http://localhost:" + port);
    System.out.println();
    for (Map.Entry<String, List<Object>> entry : DB.entrySet()) {
      System.out.printf("    /%-20s %5d records%n", entry.getKey(), entry.getValue().size());
    }
    String first = DB.isEmpty() ? "items" : DB.keySet().iterator().next();
    System.out.println();
    System.out.println("  Break it on purpose:");
    System.out.println("    http://localhost:" + port + "/" + first + "?_delay=3000");
    System.out.println("    http://localhost:" + port + "/" + first + "?_status=503");
    System.out.println("    http://localhost:" + port + "/" + first + "?_fail_rate=0.3");
    System.out.println();

    HttpServer server = HttpServer.create(new InetSocketAddress(port), 0);
    server.createContext("/", MockServer::handle);
    server.setExecutor(Executors.newFixedThreadPool(8));
    server.start();
  }

  // ------------------------------------------- a JSON reader and writer
  // The JDK has neither. This is the smallest pair that round-trips the data
  // above without pulling in a dependency and making this a build, not a file.

  static final class Json {

    private final String src;
    private int at;

    private Json(String src) {
      this.src = src;
    }

    static Object parse(String text) {
      Json parser = new Json(text);
      parser.ws();
      return parser.value();
    }

    private void ws() {
      while (at < src.length() && Character.isWhitespace(src.charAt(at))) at++;
    }

    private Object value() {
      char c = src.charAt(at);
      if (c == '{') return object();
      if (c == '[') return array();
      if (c == '"') return string();
      if (c == 't') { at += 4; return Boolean.TRUE; }
      if (c == 'f') { at += 5; return Boolean.FALSE; }
      if (c == 'n') { at += 4; return null; }
      return number();
    }

    private Map<String, Object> object() {
      Map<String, Object> out = new LinkedHashMap<String, Object>();
      at++;
      ws();
      if (src.charAt(at) == '}') { at++; return out; }
      while (true) {
        ws();
        String key = string();
        ws();
        at++; // the colon
        ws();
        out.put(key, value());
        ws();
        if (src.charAt(at++) == '}') return out;
      }
    }

    private List<Object> array() {
      List<Object> out = new ArrayList<Object>();
      at++;
      ws();
      if (src.charAt(at) == ']') { at++; return out; }
      while (true) {
        ws();
        out.add(value());
        ws();
        if (src.charAt(at++) == ']') return out;
      }
    }

    private String string() {
      StringBuilder sb = new StringBuilder();
      at++; // the opening quote
      while (true) {
        char c = src.charAt(at++);
        if (c == '"') return sb.toString();
        if (c != '\\\\') { sb.append(c); continue; }
        char esc = src.charAt(at++);
        if (esc == 'n') sb.append('\\n');
        else if (esc == 't') sb.append('\\t');
        else if (esc == 'r') sb.append('\\r');
        else if (esc == 'b') sb.append('\\b');
        else if (esc == 'f') sb.append('\\f');
        else if (esc == 'u') {
          sb.append((char) Integer.parseInt(src.substring(at, at + 4), 16));
          at += 4;
        } else sb.append(esc);
      }
    }

    /** Whole numbers stay whole. Reading 1 as a double and writing it back as
     *  "1.0" changes the data and breaks every filter on an id. */
    private Object number() {
      int start = at;
      while (at < src.length() && "-+.eE0123456789".indexOf(src.charAt(at)) >= 0) at++;
      String raw = src.substring(start, at);
      if (raw.indexOf('.') < 0 && raw.indexOf('e') < 0 && raw.indexOf('E') < 0) {
        try {
          return Long.valueOf(raw);
        } catch (NumberFormatException ignored) {
          // Too big for a long, so fall through to a double.
        }
      }
      return Double.valueOf(raw);
    }

    static String write(Object value) {
      StringBuilder sb = new StringBuilder();
      write(value, sb);
      return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private static void write(Object value, StringBuilder sb) {
      if (value == null) { sb.append("null"); return; }
      if (value instanceof String) { quote((String) value, sb); return; }
      if (value instanceof Boolean || value instanceof Number) { sb.append(text(value)); return; }
      if (value instanceof Map) {
        sb.append('{');
        boolean first = true;
        for (Map.Entry<String, Object> entry : ((Map<String, Object>) value).entrySet()) {
          if (!first) sb.append(',');
          first = false;
          quote(entry.getKey(), sb);
          sb.append(':');
          write(entry.getValue(), sb);
        }
        sb.append('}');
        return;
      }
      if (value instanceof List) {
        sb.append('[');
        boolean first = true;
        for (Object item : (List<Object>) value) {
          if (!first) sb.append(',');
          first = false;
          write(item, sb);
        }
        sb.append(']');
        return;
      }
      quote(String.valueOf(value), sb);
    }

    private static void quote(String value, StringBuilder sb) {
      sb.append('"');
      for (int i = 0; i < value.length(); i++) {
        char c = value.charAt(i);
        if (c == '"') sb.append("\\\\\\"");
        else if (c == '\\\\') sb.append("\\\\\\\\");
        else if (c == '\\n') sb.append("\\\\n");
        else if (c == '\\r') sb.append("\\\\r");
        else if (c == '\\t') sb.append("\\\\t");
        else if (c < 0x20) sb.append(String.format("\\\\u%04x", (int) c));
        else sb.append(c);
      }
      sb.append('"');
    }
  }
}
`;
}

export function csharpRunner(data) {
  return `// A mock API server. Generated by https://flakyapi.dev
//
//   dotnet run MockServer.cs        # http://localhost:4000
//   dotnet run MockServer.cs 5000   # another port
//
// That form needs .NET 10 or newer, which runs a loose file. On .NET 8 or 9,
// make a project once and drop this in as Program.cs:
//
//   dotnet new console -o mock
//   cp MockServer.cs mock/Program.cs && dotnet run --project mock
//
// No NuGet packages, no build script, no network. System.Text.Json and
// HttpListener are both in the box.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Threading.Tasks;

#nullable enable

// Embedded as a string and parsed at startup, never as C# literals: JSON's
// true/false/null are not C#'s spelling of them, and object initialisers for a
// quarter of a megabyte of data compile slower than parsing it at boot.
const string Data = ${embed(data)};

// The same controls as flakyapi.dev, so behaviour does not change when you move
// between the hosted API and this file.
const double MaxDelay = 10000;

string[] controls =
{
    "_delay", "_status", "_fail_rate", "_malformed",
    "_limit", "_page", "_start", "_sort", "_order", "_q", "_select",
};

var reserved = new HashSet<string>(controls);
var random = new Random();

var db = new Dictionary<string, JsonArray>();
foreach (var pair in JsonNode.Parse(Data)!.AsObject())
{
    if (pair.Value is JsonArray rows) db[pair.Key] = rows;
}

var port = args.Length > 0 && int.TryParse(args[0], out var chosen) ? chosen : 4000;

Console.WriteLine();
Console.WriteLine($"  flaky mock server -> http://localhost:{port}");
Console.WriteLine();
foreach (var (name, rows) in db)
{
    Console.WriteLine($"    /{name,-20} {rows.Count,5} records");
}
var first = db.Keys.FirstOrDefault() ?? "items";
Console.WriteLine();
Console.WriteLine("  Break it on purpose:");
Console.WriteLine($"    http://localhost:{port}/{first}?_delay=3000");
Console.WriteLine($"    http://localhost:{port}/{first}?_status=503");
Console.WriteLine($"    http://localhost:{port}/{first}?_fail_rate=0.3");
Console.WriteLine();

var listener = new HttpListener();

// The prefix has to differ by platform, and neither choice is arbitrary.
//
// On Linux and macOS HttpListener is managed code that opens one socket per
// address, so "localhost" and "127.0.0.1" are the same socket and asking for
// both fails with "address already in use". A wildcard binds once and answers
// to either name.
//
// On Windows it is HTTP.SYS, where a wildcard needs an administrator to reserve
// the URL first but "localhost" is granted to every user by default — so the
// wildcard that is right everywhere else is the one that would make this file
// refuse to start for most of the people running it.
var prefix = OperatingSystem.IsWindows() ? "localhost" : "*";
listener.Prefixes.Add($"http://{prefix}:{port}/");

listener.Start();

while (true)
{
    var context = await listener.GetContextAsync();
    _ = Task.Run(async () =>
    {
        try
        {
            await Handle(context);
        }
        catch (Exception error)
        {
            Console.WriteLine($"  ! {error.Message}");
            try { context.Response.Abort(); } catch { /* the caller hung up */ }
        }
    });
}

async Task Handle(HttpListenerContext context)
{
    var request = context.Request;
    Console.WriteLine($"  {request.HttpMethod} {request.Url?.PathAndQuery}");

    var query = ParseQuery(request.Url?.Query);

    if (request.HttpMethod == "OPTIONS")
    {
        await Send(context, 204, "");
        return;
    }

    // Chaos first, so a forced failure costs nothing to produce.
    var delay = Number(Get(query, "_delay"), 0);
    if (delay > 0) await Task.Delay((int)Math.Min(delay, MaxDelay));

    var rate = Number(Get(query, "_fail_rate"), 0);
    if (rate > 0 && random.NextDouble() < rate)
    {
        await Send(context, 500, ErrorBody(500, "Injected failure",
            $"Lost the dice roll for _fail_rate={Get(query, "_fail_rate")}."));
        return;
    }

    var forced = (int)Number(Get(query, "_status"), 0);
    if (forced is >= 100 and <= 599 && forced != 200)
    {
        var extra = forced is 429 or 503
            ? new Dictionary<string, string> { ["Retry-After"] = "5" }
            : null;
        await Send(context, forced, ErrorBody(forced, "Injected status", null), extra);
        return;
    }

    var parts = (request.Url?.AbsolutePath ?? "/")
        .Split('/', StringSplitOptions.RemoveEmptyEntries)
        .Select(Uri.UnescapeDataString)
        .ToList();

    if (parts.Count == 0)
    {
        var resources = new JsonArray();
        foreach (var (name, rows) in db)
        {
            resources.Add(new JsonObject
            {
                ["name"] = name,
                ["count"] = rows.Count,
                ["url"] = "/" + name,
            });
        }

        var index = new JsonObject
        {
            ["server"] = "flaky local mock",
            ["resources"] = resources,
            ["controls"] = new JsonArray(controls.Select(c => (JsonNode)c!).ToArray()),
        };
        await Send(context, 200, Fmt.Write(index));
        return;
    }

    var resource = parts[0];
    if (!db.TryGetValue(resource, out var collection))
    {
        await Send(context, 404, ErrorBody(404, $"No '{resource}' here",
            $"Available: {string.Join(", ", db.Keys)}."));
        return;
    }

    if (parts.Count > 1)
    {
        var id = parts[1];
        var found = collection.FirstOrDefault(row => Text(row?["id"]) == id);
        if (found is null)
        {
            await Send(context, 404, ErrorBody(404, $"No {resource} with id {id}", null));
            return;
        }

        await Send(context, 200, Fmt.Write(found));
        return;
    }

    var (page, total) = Query(collection, query);
    var body = Fmt.Write(new JsonArray(page.ToArray()));

    // Truncated mid-record, as a dropped connection would be.
    if (Get(query, "_malformed") == "1")
    {
        body = body[..Math.Max(1, (int)(body.Length * 0.6))];
    }

    await Send(context, 200, body, new Dictionary<string, string>
    {
        ["x-total-count"] = total.ToString(CultureInfo.InvariantCulture),
    });
}

(List<JsonNode?> rows, int total) Query(JsonArray source, Dictionary<string, string> query)
{
    IEnumerable<JsonNode?> result = source.ToList();

    foreach (var (field, wanted) in query)
    {
        if (reserved.Contains(field)) continue;
        result = result.Where(row => Text(Field(row, field)) == wanted).ToList();
    }

    var q = Get(query, "_q");
    if (!string.IsNullOrEmpty(q))
    {
        var needle = q.ToLowerInvariant();
        result = result.Where(row => Fmt.Write(row).ToLowerInvariant().Contains(needle)).ToList();
    }

    var sort = Get(query, "_sort");
    if (!string.IsNullOrEmpty(sort))
    {
        // OrderBy, not List.Sort: .NET's sort is introsort and unstable, so rows
        // with equal keys could come back in a different order from the other
        // three runners, which all sort stably. LINQ's ordering is stable.
        var comparer = Comparer<JsonNode?>.Create(Compare);
        result = Get(query, "_order") == "desc"
            ? result.OrderByDescending(row => Field(row, sort), comparer).ToList()
            : result.OrderBy(row => Field(row, sort), comparer).ToList();
    }

    var select = Get(query, "_select");
    if (!string.IsNullOrEmpty(select))
    {
        var fields = select.Split(',')
            .Select(f => f.Trim())
            .Where(f => f.Length > 0)
            .ToHashSet();
        fields.Add("id");

        result = result.Select(row =>
        {
            var slim = new JsonObject();
            if (row is JsonObject original)
            {
                foreach (var (key, value) in original)
                {
                    // A node has one parent, so the value is cloned rather than
                    // moved — reusing it would empty the row it came from.
                    if (fields.Contains(key)) slim[key] = value?.DeepClone();
                }
            }
            return (JsonNode?)slim;
        }).ToList();
    }

    var rows = result.ToList();
    var total = rows.Count;

    var limit = (int)Number(Get(query, "_limit"), 0);
    if (limit <= 0) limit = total > 0 ? total : 1;

    var start = query.ContainsKey("_start")
        ? Math.Max((int)Number(Get(query, "_start"), 0), 0)
        : (Math.Max((int)Number(Get(query, "_page"), 1), 1) - 1) * limit;

    if (start >= total) return (new List<JsonNode?>(), total);

    // Detached from the document, because a node cannot belong to two arrays.
    var slice = rows.Skip(start).Take(limit).Select(row => row?.DeepClone()).ToList();
    return (slice, total);
}

static JsonNode? Field(JsonNode? row, string name) =>
    row is JsonObject obj && obj.TryGetPropertyValue(name, out var value) ? value : null;

// Compare the way JSON spells things, not the way .NET does. A number read
// into a double and printed back can gain a ".0" that matches no filter, so
// the node's own JSON text is the answer everywhere.
static string Text(JsonNode? node)
{
    if (node is null) return "null";
    if (node is JsonValue value && value.TryGetValue<string>(out var asString)) return asString;
    return Fmt.Write(node);
}

static int Compare(JsonNode? a, JsonNode? b)
{
    if (a is null) return b is null ? 0 : 1;
    if (b is null) return -1;

    if (a is JsonValue left && b is JsonValue right
        && left.TryGetValue<double>(out var x) && right.TryGetValue<double>(out var y))
    {
        return x.CompareTo(y);
    }

    return string.CompareOrdinal(Text(a), Text(b));
}

static double Number(string? raw, double fallback) =>
    double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed) ? parsed : fallback;

static string? Get(Dictionary<string, string> query, string key) =>
    query.TryGetValue(key, out var value) ? value : null;

// First value wins, which is what the other runners do too.
static Dictionary<string, string> ParseQuery(string? raw)
{
    var query = new Dictionary<string, string>();
    if (string.IsNullOrEmpty(raw)) return query;

    foreach (var pair in raw.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries))
    {
        var split = pair.IndexOf('=');
        var key = Decode(split < 0 ? pair : pair[..split]);
        var value = split < 0 ? "" : Decode(pair[(split + 1)..]);
        if (!query.ContainsKey(key)) query[key] = value;
    }

    return query;
}

static string Decode(string raw) => Uri.UnescapeDataString(raw.Replace("+", "%20"));

static string ErrorBody(int status, string message, string? hint)
{
    var error = new JsonObject { ["status"] = status, ["message"] = message };
    if (hint is not null) error["hint"] = hint;
    return Fmt.Write(new JsonObject { ["error"] = error });
}

static async Task Send(HttpListenerContext context, int status, string body,
    Dictionary<string, string>? extra = null)
{
    var response = context.Response;
    response.StatusCode = status;
    response.ContentType = "application/json; charset=utf-8";
    response.Headers["Access-Control-Allow-Origin"] = "*";
    response.Headers["Access-Control-Allow-Methods"] = "GET, POST, PUT, PATCH, DELETE, OPTIONS";
    response.Headers["Access-Control-Allow-Headers"] = "content-type, authorization";
    response.Headers["Access-Control-Expose-Headers"] = "x-total-count";

    if (extra is not null)
    {
        foreach (var (key, value) in extra) response.Headers[key] = value;
    }

    // A 204 carries no body.
    if (status == 204)
    {
        response.ContentLength64 = 0;
        response.Close();
        return;
    }

    var bytes = Encoding.UTF8.GetBytes(body);
    response.ContentLength64 = bytes.Length;
    await response.OutputStream.WriteAsync(bytes);
    response.Close();
}

// Type declarations come after the top-level statements above. This one exists
// because a static local function cannot capture a variable, and every writer
// needs the same options.
static class Fmt
{
    // Match the other runners byte for byte. System.Text.Json escapes non-ASCII
    // and quotes to \\uXXXX by default — valid JSON, but different bytes from
    // what the hosted API sends, and it turns a readable error message into hex.
    private static readonly JsonSerializerOptions Options = new()
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    internal static string Write(JsonNode? node) => node is null ? "null" : node.ToJsonString(Options);
}
`;
}
